### PR TITLE
String to &str and replace to Builder

### PR DESCRIPTION
**Pull request by Danue1**
1. Changed String to &str for user convenience.
2. The test code has been improved to be more readable.
3. After going through the above process, the Builder Pattern looked natural, so I replaced it with the Builder Pattern.

### CODE REVIEW

**Review by lrlna — CHANGES_REQUESTED** [review]
Thank you for you PR @Danue1 ! There a few very different changes encompassed in this PR. Could I ask you to separate them out in to their own separate PRs? It will be easier for me to review and provide feedback.

**Comment by Danue1** [comment]
I will create an issue and do PR sequentially.
can i do that?

**Comment by lrlna** [comment]
@Danue1 absolutely!

**Comment by Danue1** [comment]
I will end this PR later and make an issue and make PRs sequentially.
Thank you.

**Pull request closed without merging**
