### PR TITLE
Expose whether an input definition defines a default

### PR DESCRIPTION
**Pull request by allancalix**
See https://github.com/apollographql/apollo-rs/issues/270 for motivation.

### CODE REVIEW

**Comment by lrlna** [comment]
@allancalix thank you for submitting a PR!

Input Value Definition has a Default Value field, which is an Option. This means you can run `input_definition.default_value.is_some()` to check whether that default value is present (much like you've done in this PR). With Options my preference is to usually go through this route rather write a wrapper API around `is_some()`. This signals to the user they are working with an Option, rather than hiding this fact. Is there a particular reason for your to want this wrapper?

Additionally, providing a single wrapper for this particular Option also means that all other Options in the compiler's context must have this wrapper, which is rather unmaintainable and will result in an inconsistent API.

**Comment by allancalix** [comment]
Thanks for the response. I don't have a strong preference for this over returning Option<&DefaultValue>. I'm happy to update the PR to expose the option directly.

**Comment by lrlna** [comment]
@allancalix ah! So the getter was indeed missing as @bnjjj pointed out. I've added it today https://github.com/apollographql/apollo-rs/blob/main/crates/apollo-compiler/src/queries/values.rs#L1438-L1442. If having a getter solves this for you, I'll close this PR.

**Comment by allancalix** [comment]
This change works just fine for what i'm doing, I appreciate you making the change! Closing this out.

**Pull request closed without merging**
