### PR TITLE
Extend ast::*Value node conversions

### PR DESCRIPTION
**Pull request by SimonSapin**
See respective commit messages

### CODE REVIEW

**Comment by SimonSapin** [comment]
The CI failure seems to be unrelated but due to Clippy 1.65 having a new warning

**Comment by goto-bus-stop** [comment]
the clippy warning should be addressed on main

**Review by goto-bus-stop — CHANGES_REQUESTED** [review]
this is great and something I also wanted while working on parser → encoder node conversions 😇

the changelog got auto-formatted, can you remove all the changes and only add the new entry?

**Comment by goto-bus-stop** [comment]
Would it make sense to *only* have the borrowed impls like `From<&StringValue> for String` etc? As a user you can just do `String::from(&ast_node)`, and with `ast_node.into()` it's even better. Or is there a compelling use case for the owned variants?

**Review by goto-bus-stop — APPROVED** [review]

**Review by lrlna — APPROVED** [review]
thank you!

**Comment by SimonSapin** [comment]
Sorry I didn’t check the diff! :sweat_smile: I’ve reverted the changelog formatting.

Having only the borrowed impls would be sufficient in that you can accomplish the same things, but having both means you don’t *need* to add an explicit `&` borrow if the value you have happens to be owned and not used again later. Especially when using `Into` (because type inference has enough context), you’d need parenthesis: `(&node).into()`

**Comment by goto-bus-stop** [comment]
Ahh OK I thought `node.into()` would automatically borrow it. makes sense to me!

**Comment by SimonSapin** [comment]
Uhh now I’m not sure. It might in some cases, but inference might not figure it out as often maybe? I definitely remember `(&some).thing()` with lots of generics involved.

**Pull request merged**
