### PR TITLE
DNM failing sandbox introspection query test

### PR DESCRIPTION
**Pull request by lennyburdette**
@lrlna

### CODE REVIEW

**Comment by lennyburdette** [comment]
```
thread 'test::introspection_query_from_sandbox' panicked at 'Internal error, cycle detected:

DatabaseKeyIndex { group_index: 0, query_index: 23, key_index: 0 }
DatabaseKeyIndex { group_index: 0, query_index: 8, key_index: 0 }
```

**Comment by lrlna** [comment]
closing this - test cases are part of the fix in #282 PR

**Comment by lrlna** [comment]
i closed the wrong one, oops

**Comment by lrlna** [comment]
_now_ closing in favour of #283 !

**Pull request closed without merging**
